// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WATCHDOGDATADEFINE_WATCHDOGPACKET_H_
#define FLATBUFFERS_GENERATED_WATCHDOGDATADEFINE_WATCHDOGPACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace WatchDogPacket {

struct WatchDogClientInformation;
struct WatchDogClientInformationBuilder;

enum PacketType : int8_t {
  PacketType_None = 0,
  PacketType_WatchDogStart = 1,
  PacketType_WatchDogEnd = 2,
  PacketType_MIN = PacketType_None,
  PacketType_MAX = PacketType_WatchDogEnd
};

inline const PacketType (&EnumValuesPacketType())[3] {
  static const PacketType values[] = {
    PacketType_None,
    PacketType_WatchDogStart,
    PacketType_WatchDogEnd
  };
  return values;
}

inline const char * const *EnumNamesPacketType() {
  static const char * const names[4] = {
    "None",
    "WatchDogStart",
    "WatchDogEnd",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketType(PacketType e) {
  if (::flatbuffers::IsOutRange(e, PacketType_None, PacketType_WatchDogEnd)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketType()[index];
}

enum RequestMessageType : int8_t {
  RequestMessageType_None = 0,
  RequestMessageType_Succeeded = 1,
  RequestMessageType_Failed = 2,
  RequestMessageType_MIN = RequestMessageType_None,
  RequestMessageType_MAX = RequestMessageType_Failed
};

inline const RequestMessageType (&EnumValuesRequestMessageType())[3] {
  static const RequestMessageType values[] = {
    RequestMessageType_None,
    RequestMessageType_Succeeded,
    RequestMessageType_Failed
  };
  return values;
}

inline const char * const *EnumNamesRequestMessageType() {
  static const char * const names[4] = {
    "None",
    "Succeeded",
    "Failed",
    nullptr
  };
  return names;
}

inline const char *EnumNameRequestMessageType(RequestMessageType e) {
  if (::flatbuffers::IsOutRange(e, RequestMessageType_None, RequestMessageType_Failed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRequestMessageType()[index];
}

struct WatchDogClientInformation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WatchDogClientInformationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_NAME = 4,
    VT_PROGRAM_PATH = 6,
    VT_DUMP_FILE_PATH = 8,
    VT_COMMAND_LINE_ARGV = 10,
    VT_ENABLE_RESTART = 12
  };
  const ::flatbuffers::String *program_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_NAME);
  }
  const ::flatbuffers::String *program_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_PATH);
  }
  const ::flatbuffers::String *dump_file_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DUMP_FILE_PATH);
  }
  const ::flatbuffers::String *command_line_argv() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMMAND_LINE_ARGV);
  }
  bool enable_restart() const {
    return GetField<uint8_t>(VT_ENABLE_RESTART, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_NAME) &&
           verifier.VerifyString(program_name()) &&
           VerifyOffset(verifier, VT_PROGRAM_PATH) &&
           verifier.VerifyString(program_path()) &&
           VerifyOffset(verifier, VT_DUMP_FILE_PATH) &&
           verifier.VerifyString(dump_file_path()) &&
           VerifyOffset(verifier, VT_COMMAND_LINE_ARGV) &&
           verifier.VerifyString(command_line_argv()) &&
           VerifyField<uint8_t>(verifier, VT_ENABLE_RESTART, 1) &&
           verifier.EndTable();
  }
};

struct WatchDogClientInformationBuilder {
  typedef WatchDogClientInformation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_name(::flatbuffers::Offset<::flatbuffers::String> program_name) {
    fbb_.AddOffset(WatchDogClientInformation::VT_PROGRAM_NAME, program_name);
  }
  void add_program_path(::flatbuffers::Offset<::flatbuffers::String> program_path) {
    fbb_.AddOffset(WatchDogClientInformation::VT_PROGRAM_PATH, program_path);
  }
  void add_dump_file_path(::flatbuffers::Offset<::flatbuffers::String> dump_file_path) {
    fbb_.AddOffset(WatchDogClientInformation::VT_DUMP_FILE_PATH, dump_file_path);
  }
  void add_command_line_argv(::flatbuffers::Offset<::flatbuffers::String> command_line_argv) {
    fbb_.AddOffset(WatchDogClientInformation::VT_COMMAND_LINE_ARGV, command_line_argv);
  }
  void add_enable_restart(bool enable_restart) {
    fbb_.AddElement<uint8_t>(WatchDogClientInformation::VT_ENABLE_RESTART, static_cast<uint8_t>(enable_restart), 0);
  }
  explicit WatchDogClientInformationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WatchDogClientInformation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WatchDogClientInformation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WatchDogClientInformation> CreateWatchDogClientInformation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> program_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dump_file_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> command_line_argv = 0,
    bool enable_restart = false) {
  WatchDogClientInformationBuilder builder_(_fbb);
  builder_.add_command_line_argv(command_line_argv);
  builder_.add_dump_file_path(dump_file_path);
  builder_.add_program_path(program_path);
  builder_.add_program_name(program_name);
  builder_.add_enable_restart(enable_restart);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WatchDogClientInformation> CreateWatchDogClientInformationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_name = nullptr,
    const char *program_path = nullptr,
    const char *dump_file_path = nullptr,
    const char *command_line_argv = nullptr,
    bool enable_restart = false) {
  auto program_name__ = program_name ? _fbb.CreateString(program_name) : 0;
  auto program_path__ = program_path ? _fbb.CreateString(program_path) : 0;
  auto dump_file_path__ = dump_file_path ? _fbb.CreateString(dump_file_path) : 0;
  auto command_line_argv__ = command_line_argv ? _fbb.CreateString(command_line_argv) : 0;
  return WatchDogPacket::CreateWatchDogClientInformation(
      _fbb,
      program_name__,
      program_path__,
      dump_file_path__,
      command_line_argv__,
      enable_restart);
}

inline const WatchDogPacket::WatchDogClientInformation *GetWatchDogClientInformation(const void *buf) {
  return ::flatbuffers::GetRoot<WatchDogPacket::WatchDogClientInformation>(buf);
}

inline const WatchDogPacket::WatchDogClientInformation *GetSizePrefixedWatchDogClientInformation(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<WatchDogPacket::WatchDogClientInformation>(buf);
}

inline bool VerifyWatchDogClientInformationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<WatchDogPacket::WatchDogClientInformation>(nullptr);
}

inline bool VerifySizePrefixedWatchDogClientInformationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<WatchDogPacket::WatchDogClientInformation>(nullptr);
}

inline void FinishWatchDogClientInformationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<WatchDogPacket::WatchDogClientInformation> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWatchDogClientInformationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<WatchDogPacket::WatchDogClientInformation> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace WatchDogPacket

#endif  // FLATBUFFERS_GENERATED_WATCHDOGDATADEFINE_WATCHDOGPACKET_H_
